# theme="own-dark"

[editor]
completion-timeout=5
completion-trigger-len=1
color-modes=true
end-of-line-diagnostics = "hint"
true-color=true
line-number="relative"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[editor.file-picker]
hidden=false

[editor.auto-save]
focus-lost=true
after-delay.enable=true
after-delay.timeout=50

[editor.whitespace.render]
nbsp = "all"
nnbsp = "all"
tab = "all"

[editor.soft-wrap]
enable=true

[keys.normal."\\"]
r = ":config-reload"
c = ":char"
e = ":reload-all"
s = "global_search"
