theme = "edefault"

[editor]
completion-timeout=5
completion-trigger-len=1
color-modes=true
end-of-line-diagnostics = "hint"
true-color=true
line-number="relative"
auto-format=false
bufferline="multiple"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[editor.file-picker]
hidden=false

[editor.auto-save]
focus-lost=true
after-delay.enable=true
after-delay.timeout=50

[editor.soft-wrap]
enable=true

[keys.normal."\\"]
r = ":config-reload"
c = ":char"
e = ":reload-all"
s = "global_search"
u = ":later 9999"
d = ":buffer-close"
h = "@vgh<esc>"
l = "@vgl<esc>"
